openapi: 3.2.0
info:
  title: Celonis Machine Learning Workbench Notebook Resources API
  description: Documentation for the external Machine Learning APIs. These APIs allow you to trigger executions, manage resources, and more. To access the APIs, a Bearer API Key and a team-specific AppKey must be passed in the header.
  version: v1.0
servers:
- description: Default Server URL
  url: /
security:
- authorization: []
tags:
- name: Notebook Resources
  description: The Notebook Resources API configures notebook resource such as CPU, memory, storage, and gpu.
paths:
  /api/notebooks/{id}/resources:
    get:
      tags:
      - Notebook Resources
      summary: Get Notebook Resources
      operationId: getResources
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NotebookResourcesTransport'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FrontendHandledBackendError'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExceptionReference'
    put:
      tags:
      - Notebook Resources
      summary: Update Notebook Resources
      operationId: updateResources
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotebookResourcesTransport'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/NotebookResourcesTransport'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FrontendHandledBackendError'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExceptionReference'
components:
  schemas:
    ExceptionReference:
      type: object
      properties:
        reference:
          type: string
        message:
          type: string
        shortMessage:
          type: string
    NotebookResourcesTransport:
      type: object
      properties:
        cpu:
          type: number
          format: double
        memory:
          type: integer
          format: int32
        storage:
          type: integer
          format: int32
        gpu:
          type: integer
          format: int32
      required:
      - cpu
      - memory
      - storage
    FrontendHandledBackendError:
      type: object
      properties:
        frontendErrorKey:
          type: string
        errorInformation: {}
