openapi: 3.2.0
info:
  title: Celonis Machine Learning Workbench Job Execution Group API
  description: Documentation for the external Machine Learning APIs. These APIs allow you to trigger executions, manage resources, and more. To access the APIs, a Bearer API Key and a team-specific AppKey must be passed in the header.
  version: v1.0
servers:
- description: Default Server URL
  url: /
security:
- authorization: []
tags:
- name: Job Execution Group
  description: The Job Execution Group API retrieves job execution groups.
paths:
  /api/jobs/executions/groups:
    get:
      tags:
      - Job Execution Group
      summary: Get execution groups
      operationId: getExecutionGroups
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/JobExecutionGroup'
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FrontendHandledBackendError'
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExceptionReference'
components:
  schemas:
    ExceptionReference:
      type: object
      properties:
        reference:
          type: string
        message:
          type: string
        shortMessage:
          type: string
    JobExecutionGroup:
      type: object
      properties:
        jobName:
          type: string
        lastJobExecutionId:
          type: string
        lastJobExecutionStatus:
          type: string
          enum:
          - CREATED
          - STARTED
          - RUNNING
          - COMPLETED
          - FAILED
          - CANCELED
        lastJobExecutionStartedDate:
          type: string
          format: date-time
    FrontendHandledBackendError:
      type: object
      properties:
        frontendErrorKey:
          type: string
        errorInformation: {}
